// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get Main",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "main"
                ],
                "summary": "Get Main",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CookieResponse"
                        }
                    }
                }
            }
        },
        "/moretech5": {
            "get": {
                "description": "Get Moretech5",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Moretech5"
                ],
                "summary": "Get Moretech5",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CodeResponse"
                        }
                    }
                }
            }
        },
        "/smolathon": {
            "get": {
                "description": "Get Smolathon",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Smolathon"
                ],
                "summary": "Get Smolathon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CodeResponse"
                        }
                    }
                }
            }
        },
        "/urbaton": {
            "get": {
                "description": "Get Urbaton",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Urbaton"
                ],
                "summary": "Get Urbaton",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CodeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "controller.CookieResponse": {
            "type": "object",
            "properties": {
                "cookie": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Portfolio Service API",
	Description:      "ultraevs.ru API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
