definitions:
  controller.CodeResponse:
    properties:
      code:
        type: integer
    type: object
  controller.CookieResponse:
    properties:
      cookie:
        type: string
    type: object
info:
  contact: {}
  description: ultraevs.ru API
  title: Portfolio Service API
  version: "1.0"
paths:
  /:
    get:
      description: Get Main
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CookieResponse'
      summary: Get Main
      tags:
      - main
  /moretech5:
    get:
      description: Get Moretech5
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CodeResponse'
      summary: Get Moretech5
      tags:
      - Moretech5
  /smolathon:
    get:
      description: Get Smolathon
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CodeResponse'
      summary: Get Smolathon
      tags:
      - Smolathon
  /urbaton:
    get:
      description: Get Urbaton
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CodeResponse'
      summary: Get Urbaton
      tags:
      - Urbaton
swagger: "2.0"
